import {createClient,createAccount} from 'genlayer-js'; import {studionet} from 'genlayer-js/chains';
const address=process.env.NEXT_PUBLIC_AFTERCARE_CONTRACT_ADDRESS; const key=process.env.AFTERCARE_INTEGRATION_PRIVATE_KEY;
if(!address||!key) throw new Error('Set NEXT_PUBLIC_AFTERCARE_CONTRACT_ADDRESS and AFTERCARE_INTEGRATION_PRIVATE_KEY');
const account=createAccount(key), client=createClient({chain:studionet,account});
const write=async(fn,args=[],value=0n)=>{const hash=await client.writeContract({address,functionName:fn,args,value,account});const receipt=await client.waitForTransactionReceipt({hash});console.log(fn,hash,receipt.statusName||receipt.status);return {hash,receipt};};
const read=(fn,args=[])=>client.readContract({address,functionName:fn,args});
const created=await write('create_round',['Automated StudioNet integration','Evidence-backed maintenance','2030-01-01']); const rid='round_2';
await write('fund_round',[rid],1000000000000000000n); console.log('round',await read('get_round',[rid]));
const submitted=await write('submit_claim',[rid,'Maintained a public package','Prevented deterioration','2025','https://raw.githubusercontent.com/Ifem1/aftercare/main/README.md,https://raw.githubusercontent.com/Ifem1/festiv/main/README.md']); const cid='claim_1';
const assessed=await write('assess_claim',[cid]); const claim=JSON.parse(await read('get_claim',[cid])); console.log(JSON.stringify({round:rid,claim:cid,assessment:assessed.hash,verdict:claim.verdict,payout:claim.payout})); if(Number(claim.payout)>0) await write('claim_payout',[cid]);
