'use client';
import { useState } from 'react';

const rounds = [
  { title: 'Critical dependency aftercare', tag: 'OPEN', pool: '12,400 GEN', claims: 8, desc: 'Retroactively fund the maintainers keeping core packages safe, patched, and available.', deadline: 'Closes 28 Sep 2026' },
  { title: 'Open documentation commons', tag: 'ASSESSING', pool: '6,850 GEN', claims: 14, desc: 'Support the docs, guides, and examples that stop teams repeating the same costly mistakes.', deadline: 'Assessment in progress' },
  { title: 'Quiet infrastructure fund', tag: 'FINALIZED', pool: '21,200 GEN', claims: 23, desc: 'Reward the operators who keep unglamorous but essential services online.', deadline: '3 claims paid out' },
];
export default function Home() {
  const [wallet, setWallet] = useState(false); const [modal, setModal] = useState(false); const [submitted, setSubmitted] = useState(false);
  return <main><nav><div className="brand"><span className="mark">✦</span> AFTERCARE</div><div className="navlinks"><a href="#rounds">Rounds</a><a href="#how">How it works</a><button className="wallet" onClick={()=>setWallet(!wallet)}>{wallet ? '0x71…94a2' : 'Connect wallet'}</button></div></nav>
    <section className="hero"><div className="eyebrow">RETROACTIVE PUBLIC GOODS FUNDING</div><h1>Fund what<br/><em>didn’t break.</em></h1><p className="lede">AFTERCARE rewards the people who quietly keep ecosystems healthy. GenLayer validators reconstruct the counterfactual: what would have deteriorated if they had stopped?</p><div className="hero-actions"><button className="primary" onClick={()=>setModal(true)}>Explore funding rounds <span>↗</span></button><a className="textlink" href="#how">See how it works <span>↓</span></a></div><div className="proof"><div className="avatars"><i>↗</i><i>⌁</i><i>◎</i></div><span><strong>47 contributors</strong> funded invisible work this season</span></div></section>
    <section className="signal"><div><span className="dot green"/> <strong>STUDIONET</strong><small> GenLayer network</small></div><div><strong>74,250 GEN</strong><small> allocated across 3 rounds</small></div><div><strong>45 claims</strong><small> evaluated by consensus</small></div><div className="quote">“The best public goods are the incidents that never happen.”</div></section>
    <section id="rounds" className="rounds"><div className="section-head"><div><div className="eyebrow">THE AFTERCARE INDEX</div><h2>Active funding rounds</h2></div><button className="outline" onClick={()=>setModal(true)}>+ Create a round</button></div><div className="cards">{rounds.map((r,i)=><article className="card" key={r.title} onClick={()=>i===0&&setModal(true)}><div className="card-top"><span className={'status '+r.tag.toLowerCase()}><span className="dot"/> {r.tag}</span><span className="arrow">↗</span></div><h3>{r.title}</h3><p>{r.desc}</p><div className="card-meta"><div><small>FUNDING POOL</small><strong>{r.pool}</strong></div><div><small>CLAIMS</small><strong>{r.claims}</strong></div></div><div className="card-foot"><span>{r.deadline}</span><span className="line"/></div></article>)}</div></section>
    <section id="how" className="how"><div className="eyebrow">A DIFFERENT KIND OF IMPACT</div><h2>Value is often<br/><em>what doesn’t happen.</em></h2><div className="steps">{[['01','Make a claim','Describe the maintenance work and freeze 2–4 public evidence sources.'],['02','Let consensus inspect','GenLayer validators independently retrieve the evidence and assess the counterfactual.'],['03','Claim your share','A bounded verdict becomes a transparent allocation. No committee. No guesswork.']].map(x=><div className="step" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
    <footer><div className="brand"><span className="mark">✦</span> AFTERCARE</div><span>Built for the maintenance layer of the open internet.</span><span>v0.1 · StudioNet</span></footer>
    {modal&&<div className="overlay" onClick={()=>setModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(false)}>×</button>{submitted?<><div className="success">✓</div><h2>Claim queued for assessment</h2><p>Your evidence manifest is frozen. GenLayer will retrieve and evaluate it when the round closes.</p><button className="primary" onClick={()=>setModal(false)}>Back to rounds</button></>:<><div className="eyebrow">NEW MAINTENANCE CLAIM</div><h2>What did you keep from breaking?</h2><label>CONTRIBUTION TITLE<input placeholder="e.g. Maintained the unglamorous package"/></label><label>SHORT DESCRIPTION<textarea placeholder="Describe the intervention and the deterioration it prevented…"/></label><label>EVIDENCE URLS<input placeholder="github.com/... · 2–4 public sources"/></label><button className="primary full" onClick={()=>setSubmitted(true)}>Freeze evidence & submit <span>↗</span></button><small className="note">Assessment is semantic; allocation is deterministic. Your claim is not editable after freezing.</small></>}</div></div>}
  </main>
}
